#!/bin/bash

sudo apt-get update; sudo dpkg --configure -a; sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get update && sudo apt-get dist-upgrade -y && sudo apt update && sudo apt full-upgrade -y && sudo apt-get update && sudo apt autoremove -y && sudo apt autoclean -y && sudo apt update
